### ISSUE TITLE
A permanent testing machine

### ISSUE THREAD

**Issue by vilhelmprytz** [pterodactyl-installer/pterodactyl-installer#145]
**Is your feature request related to a problem? Please describe.**
Making sure the script works well is crucial to this project. To make this happen, the script needs to be tested thoroughly. Currently, I only have the ability to test the script on Debian, Ubuntu, and CentOS on machines that do not have individual public IPs (I can, but it isn't a long-term sustainable solution).

**Describe the solution you'd like**
A permanent testing machine that has at least one dedicated IP so we can run the Vagrant virtual machines and use Let's Encrypt. I am currently not in a position where I can justify buying a server/VPS for this purpose.

**Describe alternatives you've considered**
N/A

**Additional context**
This feature request is not related to the codebase.

**Comment by shmileee** [comment]
Perhaps some Terraform sauce in conjunction with [GCloud preemptible VMs](https://cloud.google.com/preemptible-vms) could partially solve the issue :)

**Comment by vilhelmprytz** [comment]
@shmileee Thank you for the suggestion. Ideally we would like to have containers/virtual machines running 'vanilla' Linux distributions, GCP may have their own things pre-installed and other mirrors than the default ones. But this might be a good alternative, I'll look more into it! 👍

**Comment by jamesweech** [comment]
What would be the resource requirements for the VM?

**Comment by Linux123123** [comment]
So as @vilhelmprytz said it needs to have at least one dedicated IP and the ability to run vagrant (so basically needs to have virtualization enabled or if already a VM nested virtualization enabled). The system specs aren't that important, but I guess at least 1 GB ram and at least 1 core.

**Comment by vilhelmprytz** [comment]
Yes, @Linux123123 summed it up nicely. 👍

**Comment by TIKU121** [comment]
Oracle offers a 1GB RAM and 1vCPU VM for free on their [Oracle Cloud Always Free tier](https://www.oracle.com/cloud/free/).

**Comment by Linux123123** [comment]
Yes, that is correct and we will consider it, but free services can be a bit "uncontrolled" on what happens and when. Also I am not sure what Oracle Always free tier has, but for example, we had problems with the AWS free tier, because of virtualization they use, it couldn't support nested virtualization which we need for `vagrant`.

**Comment by TIKU121** [comment]
I also found a UK based host called [HostPresto](https://hostpresto.com/free-open-source-hosting/) which offers free hosting solutions to open-source projects.

**Comment by andretunes** [comment]
Hello!

I'm the Owner of a Hosting Provider. Since I liked a lot your Open-Source Project and we also use Pterodactyl Panel for personal use, I would like to provide you a free VPS in exchange of small publicity (like a Partnership). Would you like to be our Partner?

Kind regards!

**Comment by vilhelmprytz** [comment]
@andretunes Sure, I'd like to hear more! Message me on Discord or send me an email and I'll get back to you!

**Comment by andretunes** [comment]
@vilhelmprytz Sure! Will dm you ASAP.

**Comment by sinmineryt** [comment]
what happened with this?

**Comment by sebastianjnuwu** [comment]
any news?

**Comment by andretunes** [comment]
Do you need @sinjs @sebastianjnuwu ?

**Comment by zAlwaysTheSun** [comment]
Hello everyone, 
I'm Aaron, the technical manager of the French Hosting Provider PristisHeberg, and I can provide VPS totally free for infinite time if you still want.
Please contact Pristis at this email: contact@pristis.fr if you are interested.
Have a good day

**Comment by vilhelmprytz** [comment]
We have very good testing now. I don't think we need a permanent testing machine anymore.
