### ISSUE TITLE
A way to choose which installation source (e.g. branch) to install

### ISSUE THREAD

**Issue by vijaypondini** [pterodactyl-installer/pterodactyl-installer#236]
**Is your feature request related to a problem? Please describe.**
It's not 

**Describe the solution you'd like**
Basically would like us to choose a specific branch of the pterodactyls github repo so that we can see how other versions fared. For example right now the v2 branch isn't public yet but id' like to test it out

**Describe alternatives you've considered**
I manually tried to curl the panel's code into the dir but then it failed xD

**Additional context**
would really like it tbh

**Comment by vilhelmprytz** [comment]
The script currently uses the `panel.tar.gz` that the Pterodactyl team includes in every release. Unless there is something they do to package everything before release, just extracting the repo from another branch should work. If it's not, then some more work might be required. Will look into it. Thanks for the suggestion!

**Comment by vilhelmprytz** [comment]
Oh also, is this something that would be needed for Wings as well?

**Comment by Linux123123** [comment]
> The script currently uses the `panel.tar.gz` that the Pterodactyl team includes in every release. Unless there is something they do to package everything before release, just extracting the repo from another branch should work. If it's not, then some more work might be required. Will look into it. Thanks for the suggestion!

Yes they do. They change the version tags in php config and compile typescript. The version tags can be left alone, but without compiling the panel will just not work.

**Comment by vijaypondini** [comment]
Glad to know this is being worked on :) like a 10th option to choose what version we want for wings/panel

**Comment by vilhelmprytz** [comment]
@Linux123123 Could this be done with the new refactor?

**Comment by Linux123123** [comment]
Yes, but #316 would need to be adapted.

**Comment by Linux123123** [comment]
On the other hand, now that I think, supporting multiple pterodactyl version (branches or commits) would be quite difficult and almost impossible to keep up with development. More things change, then just the PHP version. A lot more variables are at play, and at least my personal belief is that it's not worth supporting that, as it would require constant support and releases. The only thing that I can think is to provide a way to install `v2` until it's released, but it's unusable in its current state.

**Comment by vilhelmprytz** [comment]
This is not something we have the resources, time or enough interest in doing currently, sorry. I'll close this issue for now, but feel free to re-open if you're also able to contribute with a PR for such feature.
