### ISSUE TITLE
/tmp/lib.sh: file does not exist

### ISSUE THREAD

**Issue by MaurOwO** [pterodactyl-installer/pterodactyl-installer#356]
**Describe the bug**
i cant 

**To Reproduce**
Steps to reproduce the behaviour:
1. open terminal as root
2. execute the command
3. See error

**Expected behaviour**
the command to work
**Screenshots**
![imagen](https://user-images.githubusercontent.com/89175228/203868290-7f684053-a491-4f88-9b30-e4d1258c11ea.png)

**OS (please complete the following information):**
 - OS: [Ubuntu]
 - Installation: [panel]

**Additional context**

**Comment by vilhelmprytz** [comment]
Do you still experience this problem? Can you please try and run the script line for line, to see why it fails to download `/tmp/lib.sh`?

**Comment by Dokman** [comment]
for me worked well when you pushed last commit

**Comment by vilhelmprytz** [comment]
Glad to hear it. I'll close this for now, then.
