### ISSUE TITLE
Certbot failed to authenticate some domains Firewalls

### ISSUE THREAD

**Issue by testibnu** [pterodactyl-installer/pterodactyl-installer#362]
![image](https://user-images.githubusercontent.com/103943757/205467187-a317232e-5eef-4798-a278-63cab35c6be8.png)

**Comment by Linux123123** [comment]
That is not related with the script. You need to have your domain's setup correctly and allowed ports through. The system firewall is automatically configured by the script, but you are still required to open ports on any external firewalls and if self-hosting port-forwarded.
