### ISSUE TITLE
Cant Run Lets Encypt

### ISSUE THREAD

**Issue by Pann09** [pterodactyl-installer/pterodactyl-installer#363]
**Screenshots**
![Screenshot (2095)](https://user-images.githubusercontent.com/110280929/205489811-7fc19d55-e85d-41c4-8b4d-1813784742f8.png)

**OS:**

- OS: Ubuntu 22 LTS
- Installation: [wings]

**Comment by vilhelmprytz** [comment]
This is not a problem with the script, most likely some firewall issue. I'd recommend to join [our Discord server](https://pterodactyl-installer.se/discord) for help with the script.
