### ISSUE TITLE
Script isn't working anymore 

### ISSUE THREAD

**Issue by Loliko1337** [pterodactyl-installer/pterodactyl-installer#364]
**Describe the bug**
I used this script in the past very often and never ha problems with it.
Today I tried to use it again but it wasn't working.
It just didn't create a few thinks, for example it didn' create an nginx file or any database

**OS (please complete the following information):**

- OS: [Ubuntu and Debian]
- Installation: [panel and wings]

**Comment by Linux123123** [comment]
The first step to troubleshooting issues is providing logs.
```bash
cat /var/log/pterodactyl-installer.log | nc termbin.com 9999
```
Without them, I can't tell you what happened.

**Comment by Bandi2021** [comment]
Can the creator please update the installation code?
nginx cannot be used

**Comment by vilhelmprytz** [comment]
> Can the creator please update the installation code? nginx cannot be used

The script works. If you have any concrete feedback, open a separate issue with detailed information about the problem. I'd advise to [join our Discord server](https://pterodactyl-installer.se/discord) for help with the script. Any bugs may be reported [here](https://github.com/pterodactyl-installer/pterodactyl-installer/issues/new/choose). Closing.
