### ISSUE TITLE
Installation doesn't start

### ISSUE THREAD

**Issue by DoZysGuy** [pterodactyl-installer/pterodactyl-installer#367]
**Describe the bug**
The script fail when I try to install panel and wings. It fail after I enter all informations, when the script start installation.

**To Reproduce**
Steps to reproduce the behaviour:

1. Enter the script command (bash <(curl -s https://pterodactyl-installer.se))
2. Select Install both panel and wings ( [2] )
3. Enter all informations
4. Then set Y for "Continue with Installation"

**Expected behaviour**
Some Urls don't seem to work

**Screenshots**
![image](https://user-images.githubusercontent.com/119410319/206138043-4f8c4f7b-6538-48d5-8863-7cc218b0f921.png)
![image](https://user-images.githubusercontent.com/119410319/206138185-6cd88362-b927-4a6b-b742-c1da5227c4ae.png)

**OS (please complete the following information):**

- OS: [Debian 10]
- Installation: [panel and wings]

**Comment by Linux123123** [comment]
You are not running on a clean system. Before running the script, you need to reinstall your OS.
