### ISSUE TITLE
Certbot failed to authenticate some domains (authenticator: nginx).

### ISSUE THREAD

**Issue by 99BlueMoon99** [pterodactyl-installer/pterodactyl-installer#369]
Domain: panel.stefanvasilescu.eu
  Type:   connection
  Detail: 130.61.214.240: Fetching http://panel.stefanvasilescu.eu/.well-known/acme-challenge/TIzUv1DWhsDyeVPF5Jtk-KXQo0tKqcsGFfdOPwUxtc8: Timeout during connect (likely firewall problem)

I don't have a lot of experience with linux. I have pointed that subdomain to the server ip and I don't know what to do.

**Comment by 99BlueMoon99** [comment]
I also opened the ports and I am using Oracle Cloud with Ubuntu 22.04.

**Comment by Linux123123** [comment]
Oracle cloud has `iptables` rule that blocks all connections by default. Join [our discord server](https://pterodactyl-installer.se/discord) for help with that, as this is not related with the script.
