### ISSUE TITLE
wings eror

### ISSUE THREAD

**Issue by amiruldev20** [pterodactyl-installer/pterodactyl-installer#372]
how to fix wings? i check systemctl status wings active. i visit my site, node eror
![Screenshot (1)](https://user-images.githubusercontent.com/73012169/206951608-39d30e08-097b-424b-b6b1-abe62f29bebf.png)

**Comment by amiruldev20** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/73012169/206953730-c5f14732-4579-403b-a2f3-1ab9f0eb8575.png)

**Comment by Linux123123** [comment]
Your panel needs to be able to access wings too. Just running them doesn't mean it will be able to reach. Check if port 8080 is open and domain if used is set up correctly. This is not a bug with script.

**Comment by amiruldev20** [comment]
all port open

**Comment by amiruldev20** [comment]
Navigated to https://goldpanel.my.id/admin/nodes
jquery.min.js?t={cache-version}:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ jquery.min.js?t={cache-version}:3
(anonymous) @ jquery.min.js?t={cache-version}:3
each @ jquery.min.js?t={cache-version}:2
each @ jquery.min.js?t={cache-version}:2
xa @ jquery.min.js?t={cache-version}:3
on @ jquery.min.js?t={cache-version}:3
bind @ jquery.min.js?t={cache-version}:4
(anonymous) @ jquery.slimscroll.min.js?t={cache-version}:15
each @ jquery.min.js?t={cache-version}:2
each @ jquery.min.js?t={cache-version}:2
slimScroll @ jquery.slimscroll.min.js?t={cache-version}:8
g.fixSidebar @ app.min.js?t={cache-version}:14
g.activate @ app.min.js?t={cache-version}:14
g @ app.min.js?t={cache-version}:14
(anonymous) @ app.min.js?t={cache-version}:14
each @ jquery.min.js?t={cache-version}:2
each @ jquery.min.js?t={cache-version}:2
b @ app.min.js?t={cache-version}:14
(anonymous) @ app.min.js?t={cache-version}:14
dispatch @ jquery.min.js?t={cache-version}:3
q.handle @ jquery.min.js?t={cache-version}:3
jquery.min.js?t={cache-version}:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ jquery.min.js?t={cache-version}:3
(anonymous) @ jquery.min.js?t={cache-version}:3
each @ jquery.min.js?t={cache-version}:2
each @ jquery.min.js?t={cache-version}:2
xa @ jquery.min.js?t={cache-version}:3
on @ jquery.min.js?t={cache-version}:3
bind @ jquery.min.js?t={cache-version}:4
(anonymous) @ jquery.slimscroll.min.js?t={cache-version}:15
each @ jquery.min.js?t={cache-version}:2
each @ jquery.min.js?t={cache-version}:2
slimScroll @ jquery.slimscroll.min.js?t={cache-version}:8
g.fixSidebar @ app.min.js?t={cache-version}:14
g.activate @ app.min.js?t={cache-version}:14
g @ app.min.js?t={cache-version}:14
(anonymous) @ app.min.js?t={cache-version}:14
each @ jquery.min.js?t={cache-version}:2
each @ jquery.min.js?t={cache-version}:2
b @ app.min.js?t={cache-version}:14
(anonymous) @ app.min.js?t={cache-version}:14
dispatch @ jquery.min.js?t={cache-version}:3
q.handle @ jquery.min.js?t={cache-version}:3
jquery.slimscroll.min.js?t={cache-version}:16 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ jquery.slimscroll.min.js?t={cache-version}:16
each @ jquery.min.js?t={cache-version}:2
each @ jquery.min.js?t={cache-version}:2
slimScroll @ jquery.slimscroll.min.js?t={cache-version}:8
g.fixSidebar @ app.min.js?t={cache-version}:14
g.activate @ app.min.js?t={cache-version}:14
g @ app.min.js?t={cache-version}:14
(anonymous) @ app.min.js?t={cache-version}:14
each @ jquery.min.js?t={cache-version}:2
each @ jquery.min.js?t={cache-version}:2
b @ app.min.js?t={cache-version}:14
(anonymous) @ app.min.js?t={cache-version}:14
dispatch @ jquery.min.js?t={cache-version}:3
q.handle @ jquery.min.js?t={cache-version}:3
jquery.min.js?t={cache-version}:4 XHR failed loading: GET "https://beta.goldpanel.my.id:8080/api/system".
send @ jquery.min.js?t={cache-version}:4
ajax @ jquery.min.js?t={cache-version}:4
(anonymous) @ nodes:259
each @ jquery.min.js?t={cache-version}:2
each @ jquery.min.js?t={cache-version}:2
pingNodes @ nodes:258
(anonymous) @ nodes:283
jquery.min.js?t={cache-version}:4 XHR failed loading: GET "https://beta.goldpanel.my.id:8080/api/system".
send @ jquery.min.js?t={cache-version}:4
ajax @ jquery.min.js?t={cache-version}:4
(anonymous) @ nodes:259
each @ jquery.min.js?t={cache-version}:2
each @ jquery.min.js?t={cache-version}:2
pingNodes @ nodes:258
setTimeout (async)
(anonymous) @ nodes:281
i @ jquery.min.js?t={cache-version}:2
add @ jquery.min.js?t={cache-version}:2
pingNodes @ nodes:280
(anonymous) @ nodes:283
jquery.min.js?t={cache-version}:4 XHR failed loading: GET "https://beta.goldpanel.my.id:8080/api/system".
send @ jquery.min.js?t={cache-version}:4
ajax @ jquery.min.js?t={cache-version}:4
(anonymous) @ nodes:259
each @ jquery.min.js?t={cache-version}:2
each @ jquery.min.js?t={cache-version}:2
pingNodes @ nodes:258
setTimeout (async)
(anonymous) @ nodes:281
i @ jquery.min.js?t={cache-version}:2
add @ jquery.min.js?t={cache-version}:2
pingNodes @ nodes:280
setTimeout (async)
(anonymous) @ nodes:281
i @ jquery.min.js?t={cache-version}:2
add @ jquery.min.js?t={cache-version}:2
pingNodes @ nodes:280
(anonymous) @ nodes:283
jquery.min.js?t={cache-version}:4 XHR failed loading: GET "https://beta.goldpanel.my.id:8080/api/system".
send @ jquery.min.js?t={cache-version}:4
ajax @ jquery.min.js?t={cache-version}:4
(anonymous) @ nodes:259
each @ jquery.min.js?t={cache-version}:2
each @ jquery.min.js?t={cache-version}:2
pingNodes @ nodes:258
setTimeout (async)
(anonymous) @ nodes:281
i @ jquery.min.js?t={cache-version}:2
add @ jquery.min.js?t={cache-version}:2
pingNodes @ nodes:280
setTimeout (async)
(anonymous) @ nodes:281
i @ jquery.min.js?t={cache-version}:2
add @ jquery.min.js?t={cache-version}:2
pingNodes @ nodes:280
setTimeout (async)
(anonymous) @ nodes:281
i @ jquery.min.js?t={cache-version}:2
add @ jquery.min.js?t={cache-version}:2
pingNodes @ nodes:280
(anonymous) @ nodes:283

**Comment by Linux123123** [comment]
You can yourself try to open `https://beta.goldpanel.my.id:8080/api/system` and see that it cannot be accessed.
