### ISSUE TITLE
Not installing. Why?

### ISSUE THREAD

**Issue by SafwanGanz** [pterodactyl-installer/pterodactyl-installer#373]
![Screenshot_2022-12-12-20-38-15-049_com termux](https://user-images.githubusercontent.com/67726326/207080404-644031eb-a400-4d19-8c03-6b7f83a58803.jpg)

**Comment by Linux123123** [comment]
You are running the installation multiple times, which is not supported. Reinstall your OS or use the uninstaller (option 6) before trying again.

**Comment by SafwanGanz** [comment]
2 times uninstalled

**Comment by Linux123123** [comment]
Clearly not, as you still have `pterodactyl` `mysql` user, which gets deleted during uninstallation.
