### ISSUE TITLE
Port 8080 not opened on ufw

### ISSUE THREAD

**Issue by LeoTheStar** [pterodactyl-installer/pterodactyl-installer#376]
This wasn't a problem a while ago, but now it is. Apparently after the panel and wings are installed, port 8080 is not opened on ufw and the panel cannot connect to the node created. It can be resolved by manually opening it but some might presume it is open.

**Comment by Linux123123** [comment]
Thanks for reporting. It's fixed in https://github.com/pterodactyl-installer/pterodactyl-installer/pull/377/commits/85caec27b018e09eaadad03bf964a309580fe09b
