### ISSUE TITLE
Installation script won't start.

### ISSUE THREAD

**Issue by real-kwellercat** [pterodactyl-installer/pterodactyl-installer#379]
**Describe the bug**
I am on debian 11 and when I run the command to install pterodactyl it gives me an error.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to a root user
2. type "sudo bash <(curl -s https://pterodactyl-installer.se)"
3. See error: bash: /dev/fd/63: No such file or directory

**Expected behaviour**
I expected the script to run.

**Screenshots**
![image](https://user-images.githubusercontent.com/89104643/210160196-26cd7a39-9cfe-4085-87cc-4bd528dedf67.png)

**OS**
- OS: Debian 11
- Installation: panel

**Comment by Linux123123** [comment]
```
Log in as root or use sudo -i before running the script.
Do not use sudo in front of the script!
```
