### ISSUE TITLE
UFW: command not found

### ISSUE THREAD

**Issue by Tonykne** [pterodactyl-installer/pterodactyl-installer#380]
**Describe the bug**
Run the script to install panel on debian 11. Fails to set up ufw. 

**To Reproduce**
Fresh Debian 11 install. Added UFW and curl to the server, and then tried to run the script.

**Expected behaviour**
I expect the server to successfully setup the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/121741979/210161083-994dadc2-2a2d-4754-8093-2e0c5e63108c.png)

- OS: Debian 11
- Installation: Panel

**Comment by apexfinity** [comment]
Has this issue been fixed?

**Comment by Linux123123** [comment]
Please provide the `$PATH`
```
echo $PATH
```

**Comment by Tonykne** [comment]
I ended up using a different distribution and had no issues :/ any logs or further information are gone now
