### ISSUE TITLE
I do not know what to do

### ISSUE THREAD

**Issue by OR1GG1N2** [pterodactyl-installer/pterodactyl-installer#381]
ion of what you expected to happen.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/83551876/211313143-73a0b0d7-e5a0-470b-a137-6dc564c6d535.png)

**OS:**
Ubuntu 22.10 x64

**Comment by Linux123123** [comment]
The script can only be run on a clean system. That means you can't run it on a system where you previously tried to install.

**Comment by norfair00** [comment]
This repo don't have kinetic 

https://ppa.launchpadcontent.net/ondrej/php/ubuntu/dists/

**Comment by norfair00** [comment]
I have clean install

**Comment by vilhelmprytz** [comment]
@norfair00 Ubuntu 22.10 is not supported by this script. Use 22.04.
