### ISSUE TITLE
Certbot failed to authenticate some domains (authenticator: nginx). The Certificate Authority reported these problems:

### ISSUE THREAD

**Issue by YoXpertguyZ** [pterodactyl-installer/pterodactyl-installer#382]
no matter what i get this error not sure why everything is setup correclty and i cant get this to work please help thanks

**Comment by apexfinity** [comment]
Hey!
I am getting the same issue, would be nice to know if this issue has a solution.
Thanks,
Apexfinity
https://apexfinity.ga

**Comment by Linux123123** [comment]
Please provide the full log first.
Script logs: ```cat /var/log/pterodactyl-installer.log | nc termbin.com 9999```

**Comment by apexfinity** [comment]
> Please provide the full log first. Script logs:
> 
> ```
> cat /var/log/pterodactyl-installer.log | nc termbin.com 9999
> ```

Dm'ed on discord.

**Comment by Linux123123** [comment]
Not related with script, but rather with your configuration not being correct. Ensure the server is accessible, all necessary ports are open and domain is set up correctly.
```
Hint: The Certificate Authority failed to verify the temporary nginx configuration changes made by Certbot. Ensure the listed domains point to this nginx server and that it is accessible from the internet.
```
