### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by InikoMatthewPro** [pterodactyl-installer/pterodactyl-installer#383]
**Describe the bug**
i try install panel on WSL, but it failed

**To Reproduce**
Steps to reproduce the behaviour:

1. Install Panel on WSL
2. See Error

**Screenshots**
![Screenshot 2023-01-13 072810](https://user-images.githubusercontent.com/109912460/212356972-f23d6f47-90ed-4d8a-a877-9bb378a9e4f3.png)

**OS (please complete the following information):**

- OS: Ubuntu  22.04 (WSL)
- Installation: Panel

**Comment by Linux123123** [comment]
WSL is not supported. You might have better luck with WSL2, but I can't guarantee that. Install proper Linux OS for the best experience.
