### ISSUE TITLE
Node will not run

### ISSUE THREAD

**Issue by apexfinity** [pterodactyl-installer/pterodactyl-installer#384]
My node wont startup, and I am getting this error.
`sudo systemctl restart wings` doesnt help.
Here is the output for wings --debug: `https://pastebin.com/YRs2F8Sq`

Appreciated if solved.

![image](https://user-images.githubusercontent.com/52583315/212504603-4d134e61-e204-409c-9e00-fb9470660020.png)
Additionally: 
![img](https://user-images.githubusercontent.com/52583315/212506326-3ea74906-3ff7-4045-9423-f8d3ec416349.png)

**Comment by Linux123123** [comment]
You don't have SSL certificates for your node.

**Comment by apexfinity** [comment]
How do I obtain them?

**Comment by Linux123123** [comment]
By running the script and choosing to obtain certificates for your node.

**Comment by apexfinity** [comment]
Is there a manual command for this?
