### ISSUE TITLE
/dev/fd/63: no such file in directory

### ISSUE THREAD

**Issue by TheAFKGamer10** [pterodactyl-installer/pterodactyl-installer#386]
When i run the bash <(curl -s https://pterodactyl-installer.se) command, it says /dev/fd/63: no such file in directory. Is there anything I'm doing wrong or did i need to install something?

**Comment by KonradStuewe** [comment]
Make sure that you don't just execute the command with sudo, but are actually logged in as root.
See here: https://www.youtube.com/watch?v=E8UJhyUFoHM

**Comment by Linux123123** [comment]
Log in as root or use `sudo -i` before running the script.
**Do not use sudo in front of the script!**
