### ISSUE TITLE
/dev/fd/61: line 112: print_list: command not found

### ISSUE THREAD

**Issue by v0ltis** [pterodactyl-installer/pterodactyl-installer#392]
When uninstalling the panel, I encounter the following error:

`/dev/fd/61: line 112: print_list: command not found`

And I guess it's one of the reason I keep getting a 500 error on nginx when I'm trying to reinstall the panel above partially-uninstalled one

logs: https://termbin.com/uo4dt

![image](https://user-images.githubusercontent.com/40314287/216837297-b937f7ba-727a-40b1-9c19-977f5b1ca7e5.png)

**Comment by Linux123123** [comment]
Yes, I can confirm that the function `print_list` doesn't exist.

The uninstallation script is not fully finished as it says when you select it
```
Uninstall panel or wings with canary version of the script (the versions that lives in master, may be broken!)"
```

**Comment by v0ltis** [comment]
Oh, my apologies, I thought he was in beta :)

then, I can't wait to have a working uninstalling system ! I'll be waiting,
thanks for your answer.

**Comment by vilhelmprytz** [comment]
@Linux123123 Is this an easy fix, removing `print_list` perhaps?

**Comment by Linux123123** [comment]
Adding it back more likely is better. Just need to pull it from a file before the major refactor.
