### ISSUE TITLE
Docker, Apparmor missing?

### ISSUE THREAD

**Issue by chloecdn** [pterodactyl-installer/pterodactyl-installer#393]
**Describe the bug**
Once installed with the Nightly Installer, on Server-Startup you get an error:
```
container@pterodactyl~ Error Event [9eb2e96c-4dd0-4725-b619-5a4c4a586192]: environment/docker: failed to start container: Error response from daemon: AppArmor enabled on system but the docker-default profile could not be loaded: running `apparmor_parser apparmor_parser --version` failed with output: 
             error: exec: "apparmor_parser": executable file not found in $PATH
```

**To Reproduce**
- Install panel & wings with nightly-script
- create a location, node, and server
- start the created server

**Expected behaviour**
- The server should start

**Screenshots**
![image](https://user-images.githubusercontent.com/80840951/216988578-a7029129-b482-4731-bbe1-8201983e17dd.png)

**OS (please complete the following information):**

- OS: Debian Debian 11
- Installation: panel & wings

**Additional context**
Can be fixed by running `sudo apt install apparmor -y`

**Comment by vilhelmprytz** [comment]
Interesting. Requires investigation, will check.

**Comment by vilhelmprytz** [comment]
This has not occured for me, and we've got no reports of it. Please feel free to re-open this if you have further information. For now, I'll close this. Thanks for reporting!
