### ISSUE TITLE
MariaDB version support

### ISSUE THREAD

**Issue by Phoenix-rat** [pterodactyl-installer/pterodactyl-installer#397]
**Describe the bug**
I tried install with script. First time I get this error.
# [info] Checking for script prerequisites.
# [warning] Found existing file at /etc/apt/sources.list.d/mariadb.list. Moving to /etc/apt/sources.list.d/mariadb.list.old_2
# [error] MariaDB Server version 10.10 is not working.
#         Please verify that the version is correct.
#         Not all releases of MariaDB are available on all distributions.
#
#         The latest MariaDB Server versions are:
#             10.3.38 10.4.28 10.5.19 10.6.12 10.7.8 10.8.7 10.9.5 10.10.3 10.11.1
#
#         More information on MariaDB releases is available at:
#             https://mariadb.com/kb/en/release-notes/

**To Reproduce**
Steps to reproduce the behaviour:

start script.
type 0 to install panel.
put the informations about panel installation.
start install.

**OS (please complete the following information):**

- Ubuntu 18.04.5 LTS x86_64
- Installation: panel and wing

**Comment by vilhelmprytz** [comment]
Thanks for reporting. @Linux123123, have you seen this issue occur for others?

**Comment by Phoenix-rat** [comment]
I found what is problem
MariaDB isn't support Ubuntu 18.04

**Comment by vilhelmprytz** [comment]
Next release skips Ubuntu 18.04 release. Sorry for the inconvenience caused.
