### ISSUE TITLE
Node doesn't seem to be working correctly

### ISSUE THREAD

**Issue by Purcify92** [pterodactyl-installer/pterodactyl-installer#399]
Red heart next to the node, for some reason the panel is using the node address instead of the panel address, and storage units are in MiB instead of MB (idk if this is intentional if it is can someone show me how to change it?)

- OS: Ubuntu 22.04
- Installation: panel and wings

![image](https://user-images.githubusercontent.com/83446248/219937005-6740b31d-5f50-4224-956e-f6c795d9028d.png)
![image](https://user-images.githubusercontent.com/83446248/219937017-68e5e85c-52c9-4400-804f-eaae29fdbba8.png)
![image](https://user-images.githubusercontent.com/83446248/219937028-cd5ee319-0eea-4221-b1d7-de9f02c4f481.png)
![image](https://user-images.githubusercontent.com/83446248/219937040-2cc7d929-25f3-4e5f-9baa-d5f55b67e555.png)
(this shows up when going to the link shown in the console error):
![image](https://user-images.githubusercontent.com/83446248/219937078-c7725e38-397c-4ee4-aeb2-50e5e2d4007c.png)

**Comment by vilhelmprytz** [comment]
This is not a problem with the script. Please refer to the [Discord server](https://pterodactyl-installer.se/discord) for help with the script itself. Closing.
