### ISSUE TITLE
Panel wont install on Ubuntu 20.04

### ISSUE THREAD

**Issue by FuchsFuchs1** [pterodactyl-installer/pterodactyl-installer#403]
**Describe the bug**
Panel wont install on Ubuntu 20.04

**To Reproduce**
run "bash <(curl  -s https://raw.githubusercontent.com/pterodactyl-installer/pterodactyl-installer/master/installers/panel.sh )"

**Expected behaviour**
```
/dev/fd/63: line 35: /tmp/lib.sh: No such file or directory
 curl: (3) URL using bad/illegal format or missing URL
 * ERROR: Could not load lib script
``` 

**OS (please complete the following information):**
Ubuntu 20.04
Didnt try wings yet

**Additional context**
Its on a Contabo VPS

**Comment by Linux123123** [comment]
That is not the command to run script. Use
```bash
bash <(curl -s https://pterodactyl-installer.se/)
```
