### ISSUE TITLE
How to fix Error Still Asums SSL. My panel not runing

### ISSUE THREAD

**Issue by rizkisquadpants** [pterodactyl-installer/pterodactyl-installer#404]
![Screenshot_2023-03-08-10-27-44-71_61c78dc80ee02b53007c815fefe993e3](https://user-images.githubusercontent.com/28975688/223613247-f92e923e-9a9e-4808-ac3e-590f448a3786.jpg)

**Comment by Linux123123** [comment]
The error is clearly written.

Timeout (likely a firewall problem)

The script only runs letsencypt and you are responsible to have the firewall that is external to the system set up correctly.
