### ISSUE TITLE
Installer is stuck at "Processing triggers for man-db (2.9.4-2) 

### ISSUE THREAD

**Issue by Justin2211** [pterodactyl-installer/pterodactyl-installer#405]
![Installer](https://user-images.githubusercontent.com/36715641/225390109-1355b6cd-4dc9-4def-9606-ba70e7202acb.png)

The server runs under the following:
Debian 11.
16 GB RAM.

No errors actually came before that. This happens now at the end of the Wings installation.
Can anyone tell me if it is normal to have to wait longer?
It's been about 15 minutes and my default website is no longer available.

Sincerely.

**Comment by Linux123123** [comment]
It's not a problem with script, as it hangs on `apt` install step, which we do not control after running. It's most likely something wrong with your server.
