### ISSUE TITLE
XHR failed: NPM issue with setup 

### ISSUE THREAD

**Issue by kiritodragneel** [pterodactyl-installer/pterodactyl-installer#407]
Okay so I installed with all the defaults etc... set my domain to panel.mydomain.uk etc...
And the panel works no issuess at all, the node is setup on node.mydomain.uk forwarding 8080 

However when I go to add a node I just get the following in browser console 
XHR failed loading: GET "https://node.mydomain.uk:8080/api/system".

I have tried everything to fix, I changed to use local ip instead of domain, 
I changed to use different ports. 
I added * to trusted proxies in the .env of the panel

I do not know what else to do to get the panel online :(

EDIT: I should add my ISP does not allow uhh god whats it called Callback URL or something IE: I can't go to mydomain.uk while on the same network. I must use IPs

**Comment by Linux123123** [comment]
Duplicate #402
