### ISSUE TITLE
No way to select DNS-01 auth challenge

### ISSUE THREAD

**Issue by Leapo** [pterodactyl-installer/pterodactyl-installer#410]
**Describe the bug**
When running the installation script, LetsEncrypt automatically attempts an HTTP-01 auth challenge, which fails, because I use DNS-01 auth challenges via CloudFlare's API.

No option to use a DNS-01 auth challenge is ever presented, no certs get generated, and the resulting install is broken.

**To Reproduce**
Run the installation script as directed by the readme. No option to do a DNS-01 auth challenge is ever presented.

**Expected behaviour**
I should be prompted for the option to configure a DNS-01 challenge, then prompted for my DNS provider's API token.

**Operating System**
Rocky Linux 9.1

**Comment by Leapo** [comment]
Additionally, I went ahead and configured certificates manually by following the official docs here:
https://pterodactyl.io/tutorials/creating_ssl_certificates.html#method-2:-acme.sh-(using-cloudflare-api)

Once signed in to Pterodactyl, I created a location and a node, completed Wings setup, and... none of my nodes work. They all show a red heart with the error "Error connecting to node!"

**Comment by Linux123123** [comment]
HTTP-01 auth challenge doesn't fail with Cloudflare. It works with Cloudflare, just as well as with any other DNS provider. Check your configuration for any issues. You can read my response in #374 on this issue.

**Comment by Leapo** [comment]
It fails because I use DNS-01 auth exclusively. No ports are forwarded, so HTTP-01 will never work. It's not a configuration issue, it's intimational.

So, can we can get the option to use DNS-01 during setup added?
