### ISSUE TITLE
Error with "LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php"

### ISSUE THREAD

**Issue by Odysseum04** [pterodactyl-installer/pterodactyl-installer#413]
Hello guys, first of all thank you for your amazing work ! It saves me a lot of time every weeks !

**Describe the bug**
Adding 'ppa:ondrej/php' result in a timed out operation in the pterodactyl (PANEL) installation on the latest 22.04 ubuntu server update.

**To Reproduce**
Steps to reproduce the behaviour:

1. Use the script with option 0 (panel installation)
2. Finish the installation process with classical informations (I myself used a local ip instead of a domain name)
3. Wait until the "adding 'universe' to all repositories" since "LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php" command come just after in the script.

**Expected behaviour**
A finished panel installation

**LOGS**
odysseum04@vm1:~$ su
Password: 
root@vm1:/home/odysseum04# cd /
root@vm1:/# bash <(curl -s https://pterodactyl-installer.se)
* Retrieving release information...
######################################################################
* Pterodactyl panel installation script @ v0.12.3
* 
* Copyright (C) 2018 - 2023, Vilhelm Prytz, <vilhelm@prytznet.se>
* https://github.com/pterodactyl-installer/pterodactyl-installer
* 
* This script is not associated with the official Pterodactyl Project.
* 
* Running ubuntu version 22.04.
######################################################################
* What would you like to do?
* [0] Install the panel
* [1] Install Wings
* [2] Install both [0] and [1] on the same machine (wings script runs after panel)
* [3] Install panel with canary version of the script (the versions that lives in master, may be broken!)
* [4] Install Wings with canary version of the script (the versions that lives in master, may be broken!)
* [5] Install both [3] and [4] on the same machine (wings script runs after panel)
* [6] Uninstall panel or wings with canary version of the script (the versions that lives in master, may be broken!)
* Input 0-6: 2
* Retrieving release information...
######################################################################
* Pterodactyl panel installation script @ v0.12.3
* 
* Copyright (C) 2018 - 2023, Vilhelm Prytz, <vilhelm@prytznet.se>
* https://github.com/pterodactyl-installer/pterodactyl-installer
* 
* This script is not associated with the official Pterodactyl Project.
* 
* Running ubuntu version 22.04.
* Latest pterodactyl/panel is v1.11.3
######################################################################
* Database configuration.
* 
* This will be the credentials used for communication between the MySQL
* database and the panel. You do not need to create the database
* before running this script, the script will do that for you.
* 
* Database name (panel): 
* Database username (pterodactyl): 
* Password (press enter to use randomly generated password): 
* List of valid timezones here https://www.php.net/manual/en/timezones.php
* Select timezone [Europe/Stockholm]: Europe/Brussels
* Provide the email address that will be used to configure Let's Encrypt and Pterodactyl: clement.raes@gmail.com
* Email address for the initial admin account: clement.raes@gmail.com
* Username for the initial admin account: Odysseum04
* First name for the initial admin account: Clément
* Last name for the initial admin account: Raes
* Password for the initial admin account: *****************
########################################################################
* Set the FQDN of this panel (panel.example.com): 192.168.129.8

* WARNING: * Let's Encrypt will not be available for IP addresses.

* To use Let's Encrypt, you must use a valid domain name.
* Do you want to automatically configure UFW (firewall)? (y/N): y
##############################################################
* Pterodactyl panel v1.11.3 with nginx on ubuntu
* Database name: panel
* Database user: pterodactyl
* Database password: (censored)
* Timezone: Europe/Brussels
* Email: (censored)
* User email: clement.raes@gmail.com
* Username: Odysseum04
* First name: (censored)
* Last name: (censored)
* User password: (censored)
* Hostname/FQDN: 192.168.129.8
* Configure Firewall? true
* Configure Let's Encrypt? false
* Assume SSL? false
##############################################################

* Initial configuration completed. Continue with installation? (y/N): y
* Starting installation.. this might take a while!
* Installing dependencies for ubuntu 22.04...
Atteint :1 http://be.archive.ubuntu.com/ubuntu jammy InRelease
Réception de :2 http://be.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Réception de :3 http://be.archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB]
Réception de :4 http://be.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Réception de :5 http://be.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [672 kB]
Réception de :6 http://be.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [920 kB]
1 929 ko réceptionnés en 3s (740 ko/s)
Lecture des listes de paquets…
* 
* Installing Uncomplicated Firewall (UFW)
Firewall is active and enabled on system startup

* SUCCESS: Enabled Uncomplicated Firewall (UFW)

* Opening ports: 22 (SSH), 80 (HTTP) and 443 (HTTPS)
Rule added
Rule added (v6)
Rule added
Rule added (v6)
Rule added
Rule added (v6)
Firewall reloaded

* SUCCESS: Firewall ports opened!

Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
ca-certificates est déjà la version la plus récente (20230311ubuntu0.22.04.1).
ca-certificates passé en « installé manuellement ».
gnupg est déjà la version la plus récente (2.2.27-3ubuntu2.1).
gnupg passé en « installé manuellement ».
software-properties-common est déjà la version la plus récente (0.99.22.7).
software-properties-common passé en « installé manuellement ».
Les paquets suivants ont été installés automatiquement et ne sont plus nécessaires :
  libflashrom1 libftdi1-2
Veuillez utiliser « apt autoremove » pour les supprimer.
Les NOUVEAUX paquets suivants seront installés :
  apt-transport-https
0 mis à jour, 1 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 1 510 o dans les archives.
Après cette opération, 169 ko d'espace disque supplémentaires seront utilisés.
Réception de :1 http://be.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 apt-transport-https all 2.4.9 [1 510 B]
1 510 o réceptionnés en 1s (2 566 o/s)
                                      Sélection du paquet apt-transport-https précédemment désélectionné.
(Lecture de la base de données... 77205 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../apt-transport-https_2.4.9_all.deb ...
Dépaquetage de apt-transport-https (2.4.9) ...
Paramétrage de apt-transport-https (2.4.9) ...
NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 5.15.0-73-generic
NEEDRESTART-KEXP: 5.15.0-73-generic
NEEDRESTART-KSTA: 1
Atteint :1 http://be.archive.ubuntu.com/ubuntu jammy InRelease
Atteint :2 http://be.archive.ubuntu.com/ubuntu jammy-updates InRelease
Réception de :3 http://be.archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB]
Atteint :4 http://be.archive.ubuntu.com/ubuntu jammy-security InRelease
108 ko réceptionnés en 1s (73,5 ko/s)
Lecture des listes de paquets…
**Adding component(s) 'universe' to all repositories.**
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 364, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
  File "/usr/bin/add-apt-repository", line 347, in main
    shortcut = handler(source, **shortcut_params)
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 82, in __init__
    if self.lpppa.publish_debug_symbols:
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 120, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 107, in lpteam
    self._lpteam = self.lp.people(self.teamname)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 98, in lp
    self._lp = login_func("%s.%s" % (self.__module__, self.__class__.__name__),
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 494, in login_anonymously
    return cls(
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 230, in __init__
    super(Launchpad, self).__init__(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 472, in __init__
    self._wadl = self._browser.get_wadl_application(self._root_uri)
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 447, in get_wadl_application
    response, content = self._request(url, media_type=wadl_type)
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 389, in _request
    response, content = self._request_and_retry(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 359, in _request_and_retry
    response, content = self._connection.request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1725, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 144, in _request
    response, content = super(LaunchpadOAuthAwareHttp, self)._request(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 184, in _request
    return super(RestfulHttp, self)._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1363, in _conn_request
    conn.connect()
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1153, in connect
    sock.connect((self.host, self.port))
TimeoutError: [Errno 110] Connection timed out
* Installation of panel completed. Do you want to proceed to wings installation? (y/N): y

**OS (please complete the following information):**

- OS: [e.g. Ubuntu 22.04 server latest update]
- Installation: [panel]

**Additional context**
Used a local ip and a virtual machine but I have already done this a few times and it always worked.

**Comment by Linux123123** [comment]
```TimeoutError: [Errno 110] Connection timed out``` it is a problem with your network connection.

We do not control how this command works, we only use it. It is provided with Ubuntu, so the script is not at fault.
