### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by Synlax** [pterodactyl-installer/pterodactyl-installer#414]
* Initial configuration completed. Continue with installation? (y/N): y
* Starting installation.. this might take a while!
* Installing dependencies for ubuntu 22.10...
Hit:1 http://security.ubuntu.com/ubuntu kinetic-security InRelease
Ign:2 https://ppa.launchpadcontent.net/ondrej/php/ubuntu kinetic InRelease
Hit:3 http://europe-central2-a.gce.clouds.archive.ubuntu.com/ubuntu kinetic InRelease
Hit:4 http://europe-central2-a.gce.clouds.archive.ubuntu.com/ubuntu kinetic-updates InRelease
Err:5 https://ppa.launchpadcontent.net/ondrej/php/ubuntu kinetic Release
  404  Not Found [IP: 185.125.190.52 443]
Hit:6 http://europe-central2-a.gce.clouds.archive.ubuntu.com/ubuntu kinetic-backports InRelease
Reading package lists...
E: The repository 'https://ppa.launchpadcontent.net/ondrej/php/ubuntu kinetic Release' does not have a Release file.
![image](https://github.com/pterodactyl-installer/pterodactyl-installer/assets/95689349/39f377a4-791a-460f-9d6b-a8edaed85206)

Ubuntu 22.10

**Comment by Linux123123** [comment]
Ubuntu 22.10 is not supported.
