### ISSUE TITLE
Debian 12 support

### ISSUE THREAD

**Issue by LDprg** [pterodactyl-installer/pterodactyl-installer#416]
Well is not working under Debian 12 because of "unsupported OS" Error. Please add support!

**Comment by Linux123123** [comment]
It will get the support down the line. It's still quite new and most people still use 11. But it is definently on the radar.

**Comment by vilhelmprytz** [comment]
We'll make sure to introduce support after Debian has released the first point release, 12.1. Thanks for opening the issue!

**Comment by vegas003** [comment]
+1 i got confused when i saw the Unsupported OS error

**Comment by TechGamerExpert** [comment]
+1

**Comment by taehas** [comment]
+1 hopefully it gets supported soon! in the meantime is there a way to bypass the error?

**Comment by Linux123123** [comment]
No, this is not an error. The script is not configured to work with it at the moment.

**Comment by vilhelmprytz** [comment]
This will be released within the next 24h.
