### ISSUE TITLE
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax

### ISSUE THREAD

**Issue by mtojay** [pterodactyl-installer/pterodactyl-installer#417]
**Describe the bug**
fresh install on a fresh install of debian 11. script runs through all steps until it arrives at:

* Creating database user pterodactyl...
* Database user pterodactyl created
* Creating databasepanel...
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '4\0008\0008\001B[3~\001B[3~\001B[3~paN\0008N\0008nae\0008\0008el' at line 1

**To Reproduce**
install pterodactyl with the script

**Expected behaviour**
expected it to work

**Screenshots**

**OS (please complete the following information):**

- OS: [e.g. Ubuntu, Debian, CentOS]
debian 11

- Installation: [panel or wings]
panel

**Comment by Linux123123** [comment]
This script is not designed to work on **non clean** systems or **repeated installations**.
Also the password used needs to work with mysql as some passwords give this error too.

Please try again and if you still have the error please reopen the issue.

**Comment by mtojay** [comment]
system was clean. (freshly spun up proxmox vm for the sole purpose of using pterodactyl on it)

but it seems like the problem was the mysql password. because it works now if i use a simpler one with just numbers. (bit ocd with passwords and went overboard probably) 

thx for your help.
