### ISSUE TITLE
Error connecting to node

### ISSUE THREAD

**Issue by FizzGamingJR** [pterodactyl-installer/pterodactyl-installer#418]
**Describe the bug**
Upon installing and attempting to make a node an error appears saying "Error connecting to node! Check browser console for details."
I have looked at my browser console by pressing CTRL + SHIFT + J which shows no errors whatsoever even after refreshing a few times and allowing the node to load its status.

**To Reproduce**
Unsure how to reproduce as I do not know what is causing this issue.

**Expected behaviour**
From my understanding, the node should appear online after all dependencies and installation processes have been complete such as adding the config to the config.ymt, and reloading and starting systemd and Wings.

**Screenshots**
![image](https://github.com/pterodactyl-installer/pterodactyl-installer/assets/28313136/3ed99f51-6c74-41f6-9602-7da346016407)

![image](https://github.com/pterodactyl-installer/pterodactyl-installer/assets/28313136/400214d7-403c-4980-a570-f8cfee75f6ae)

**OS (please complete the following information):**

- OS: Ubuntu 20.04
- Installation: Not sure what this means, I initially installed panel but later altered and started Wings as instructed by a tutorial.

**Additional context**
This is my first time installation of pterodactyl which is probably apparent from the getgo, apologies if I cannot answer some required information with the necessary details due to my lack of knowledge on this subject. I followed a YouTube tutorial from start to end, dotting the i and crossing the T but unfortunately I ran into this issue. I tried requesting support from the channel but they don't seem very active anymore and tend to only assist those who are customers of theirs. Cheers in advance if anybody is able to help me!

**Comment by FizzGamingJR** [comment]
Anybody able to assist please? Throughout today I have completely factory reset my VPS and followed another tutorial (Made by somebody else) and I am still encountering this issue. Wings has been started and the VPS has been restarted after the installation but I'm yet still getting the Error connecting to node problem.

**Comment by vilhelmprytz** [comment]
@FizzGamingJR Sorry for the delay. Check that wings is running. You can try and reach wings directly via your browser to see if it's working (just visit the IP/fqdn of your server on port 8080). I'd recommend joining our [Discord server](https://pterodactyl-installer.se/discord) for help with the script. I'll close this issue but feel free to reach out via the Discord server or reopen this issue if it turns out that there is a problem with the script.

**Comment by FizzGamingJR** [comment]
> @FizzGamingJR Sorry for the delay. Check that wings is running. You can try and reach wings directly via your browser to see if it's working (just visit the IP/fqdn of your server on port 8080). I'd recommend joining our [Discord server](https://pterodactyl-installer.se/discord) for help with the script. I'll close this issue but feel free to reach out via the Discord server or reopen this issue if it turns out that there is a problem with the script.

Hi there, thank you for your reply, apologies if I sound quite impatient in the message you replied to, been attempting to get support all week on the official Pterodactyl Discord but they seem to be bot support motivated rather than human beings.
It seems that nobody has been able to help me on your guys Discord Server, although I've seen a few people with the same issue as mine with some saying that it was working previously and the suddenly ran into errors, which obviously I cannot relate to as this is my first time installation.
With that in mind, and with me actually attempting everything I've been suggested to do, is it possible that they is a bug with the script itself?
It also seems that my fqdn on port 8080 seems to time out when attempting to connect on my local system, wings has been started, stopped and restarted and the Node isn't infinitely loading when I click into it, it only states that there is an error connecting as shown on the screenshots provided.

**Comment by vilhelmprytz** [comment]
@FizzGamingJR I'm sorry to hear that. Unfortunately, there is not enough information in this ticket to debug the problem, but I'd guess that there is a problem with your firewall. Check that wings is running with `systemctl status wings` and if it's running, check that you can reach it from your browser by visiting `https://<fqdn of node running wings>:8080`. If not, then it's a problem with your firewall.

**Comment by FizzGamingJR** [comment]
> @FizzGamingJR I'm sorry to hear that. Unfortunately, there is not enough information in this ticket to debug the problem, but I'd guess that there is a problem with your firewall. Check that wings is running with `systemctl status wings` and if it's running, check that you can reach it from your browser by visiting `https://<fqdn of node running wings>:8080`. If not, then it's a problem with your firewall.

Mr Vilhelmprytz, your a legend my friend. It seems that the VPS Host I am using has not only an internal firewall actual within the VPS, but also on the management panel that required me to add 8080, and 2022 as ports on there, that has fixed the issue completely.
I do very much appreciate your support, you have helped me more than anybody else in the past week of trying to troubleshoot this issue.
You have fantastic rest of your day!
