### ISSUE TITLE
I cant reach my panel when using namecheap domain

### ISSUE THREAD

**Issue by Rustbreaker17** [pterodactyl-installer/pterodactyl-installer#419]
**Describe the bug**
When I install the panel with a domain from namecheap mostly SSL verification does not verify and does the domain does not transfer you to the panel the domain points to my server ip

**To Reproduce**
I am unsure how to reproduce this try using a namecheap domain.

**OS:**

-Ubuntu 22

**Comment by Linux123123** [comment]
Not enough information please add script log.
```bash
cat /var/log/pterodactyl-installer.log | nc termbin.com 9999
```

**Comment by vilhelmprytz** [comment]
Please refer to the "Discussion" feature here on GitHub, or to our official [Discord server](https://pterodactyl-installer.se/discord).
