### ISSUE TITLE
Link for terms of service for lets encrypt now working

### ISSUE THREAD

**Issue by Beijing-corn87** [pterodactyl-installer/pterodactyl-installer#420]
Hi just a heads up that the link for the terms of service for let's Encrypt now working and just takes you to an error 404 page. 
![image](https://github.com/pterodactyl-installer/pterodactyl-installer/assets/111331826/9b572678-1cd4-4160-ba53-8e30126708bf)

**Comment by Linux123123** [comment]
We do not control the link, as it is provided by the `certbot `package. Please open an issue on their respective repository.
