### ISSUE TITLE
panel.sh

### ISSUE THREAD

**Issue by AntyBD** [pterodactyl-installer/pterodactyl-installer#424]
Crash on installation stage (Ubuntu 20.04 x64)
'universe' distribution component is already enabled for all sources.

**Comment by Linux123123** [comment]
That shouldn't crash the script. Please provide the full log of installation.
```cat /var/log/pterodactyl-installer.log | nc termbin.com 9999```

**Comment by vilhelmprytz** [comment]
@AntyBD Have you tried to run this on a clean installation of Ubuntu 20.04 again?

**Comment by AntyBD** [comment]
@vilhelmprytz Yes

**Comment by vilhelmprytz** [comment]
@AntyBD And it's still the same problem?

**Comment by AntyBD** [comment]
@vilhelmprytz Yes

**Comment by vilhelmprytz** [comment]
@Linux123123 Maybe we should add `|| true` to the end of this so that it doesn't "fail"?

https://github.com/pterodactyl-installer/pterodactyl-installer/blob/34bd7dd02fbb297e31bd92831c2e006872091598/installers/panel.sh#L253

**Comment by Linux123123** [comment]
I am just not sure if that is the place where it fails. If it is already added, it's the same return code and shouldn't cause a fail.
```bash
root@e963ab3c4b31:/# add-apt-repository universe -y
'universe' distribution component enabled for all sources.
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
root@e963ab3c4b31:/# echo $?
0
root@e963ab3c4b31:/# add-apt-repository universe -y
'universe' distribution component is already enabled for all sources.
root@e963ab3c4b31:/# echo $?
0
```

**Comment by TheCiROMG** [comment]
It may be that my comment is of no use, but, before anything else, install the dependencies, update and upgrade, then just there, use the script, I did not have any problems with Ubuntu 22.04

**Comment by navin-hariharan** [comment]
![image](https://github.com/pterodactyl-installer/pterodactyl-installer/assets/42506955/df1a7d14-e00e-43db-8574-1993b7cf529f)
I am getting this error!

**Comment by navin-hariharan** [comment]
oracle instance! ubuntu 20.04

**Comment by vilhelmprytz** [comment]
Closing this for now. Feel free to reopen if this issue persists.
