### ISSUE TITLE
I am using windows right now how can i use this on windows or what are the steps to make it useable

### ISSUE THREAD

**Issue by PsxScriptsW** [pterodactyl-installer/pterodactyl-installer#427]
**Is your feature request related to a problem? Please describe.**
help
**Describe the solution you'd like**
how can i use this on windows
**Describe alternatives you've considered**
none
**Additional context**

**Comment by Linux123123** [comment]
We do not support windows or WSL.  WSL2 might work, but can't guarantee. We will probably never officially support anything windows related.
