### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by Derbosik** [pterodactyl-installer/pterodactyl-installer#429]
**Describe the bug**
Close to the end of installation, MySQL access is denied.

**To Reproduce**
Steps to reproduce the behaviour:

1. Start installation with option 2.
2. Proceed with the installation
3. The installation fails after "Creating database user pterodactyluser..."
4. Error 'ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)' is displayed

**Expected behaviour**
It shouldn't fail

**OS (please complete the following information):**

- OS: Debian 12 (Default Contabo configuration)
- Installation: Both (Number 2)

**Comment by vilhelmprytz** [comment]
Have you tried to run this again, but with another password? This looks to me like the password you've used is not valid.

**Comment by Derbosik** [comment]
I used my database credentials, they are valid

**Comment by Baba1408** [comment]
I have exactly the same problem, but when I reinstall the panel it always happens, I've even avoided the "!" and ";" in the passwords.

**Comment by vilhelmprytz** [comment]
There are probably unsupported characters in the password. The validation is bad for this, but I don't think this is a direct problem with the script. If it still fails when you do not use certain special characters, feel free to re-open.

**Comment by Neotastisch** [comment]
Same Problem even with just numbers and letters

**Comment by stressatoo** [comment]
can reproduce

> Same Problem even with just numbers and letters
