### ISSUE TITLE
Installer Download Error

### ISSUE THREAD

**Issue by KICKGodz** [pterodactyl-installer/pterodactyl-installer#432]
**Describe the bug**
The script fails to download packages

**To Reproduce**
Run the script and get to the Let's Encrypt Question

**Expected behaviour**
Should download fine

**Screenshots**
![Screen Shot 2023-08-30 at 12 24 38 PM](https://github.com/pterodactyl-installer/pterodactyl-installer/assets/48659268/fc1d4137-13b9-4b80-bd65-dfbc3ca93cb9)

**OS (please complete the following information):**

- OS: Ubuntu 22.04 Arm64
- Installation: Both (2)

**Additional context**
It knows that I am on a ARM computer

**Comment by Linux123123** [comment]
Please use a clean installation of the OS and make sure you have a stable internet connection.

**Comment by KICKGodz** [comment]
It seems I ended up fixing it by ignoring the Let's Encrypt

**Comment by KICKGodz** [comment]
Figured out the problem, it was because i386 arch was added. In order to remove it I had to run
```
sudo dpkg --remove-architecture i386
```
