### ISSUE TITLE
ERROR 1396 (HY000)

### ISSUE THREAD

**Issue by PanzXx** [pterodactyl-installer/pterodactyl-installer#433]
RROR 1396 (HY000) at line  1: Operation CREATE USER failed for 'pterodactyl'@'127.0.0.1

**Comment by Baba1408** [comment]
I have exactly the same thing

**Comment by CatPaulKatze** [comment]
the pterodactyl user exist already. That is no Problem at the pterodactyl-installer side, but on your side

**Comment by vilhelmprytz** [comment]
As mentioned, this is not a problem with the script. Closing for now.
