### ISSUE TITLE
Ubuntu 23.04

### ISSUE THREAD

**Issue by kittenvr** [pterodactyl-installer/pterodactyl-installer#440]
**Describe the bug**
seams to be incompatibe with Ubuntu 23.04

**To Reproduce**
Steps to reproduce the behaviour:
install Ubuntu 23.04
run script

**Expected behaviour**
it runs without errors

**Screenshots**

**OS (please complete the following information):**
Ubuntu 23.04

- OS: [e.g. Ubuntu, Debian, CentOS]
- Installation: [both]

**Additional context**

**Comment by Linux123123** [comment]
We're not actively supporting this release of Ubuntu. We don't have intentions of supporting these non LTS versions of Ubuntu.
