### ISSUE TITLE
wings probs

### ISSUE THREAD

**Issue by xTz11** [pterodactyl-installer/pterodactyl-installer#442]
During the wings installation on a fresh server .. :/

* SUCCESS: Dependencies installed!

* Downloading Pterodactyl Wings..
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to github.com:443

- OS:  Debian 11
- Installation: [wings]

**Comment by xTz11** [comment]
i m not behind proxy or using vpn ...

**Comment by Diamondy01** [comment]
You can try again using pterodactyl documentation

**Comment by vilhelmprytz** [comment]
This is not a problem with the script. Make sure you can reach GitHub.

**Comment by xTz11** [comment]
Yeah fixed, it was ufw blockinfg the port .. i dunno why..

**Comment by Diamondy01** [comment]
I recommend closing this now
