### ISSUE TITLE
config nginx

### ISSUE THREAD

**Issue by TheFairwol** [pterodactyl-installer/pterodactyl-installer#445]
![image](https://github.com/pterodactyl-installer/pterodactyl-installer/assets/146767637/96a36d08-6e65-4f43-bb37-f1bb18ea1462)
![image](https://github.com/pterodactyl-installer/pterodactyl-installer/assets/146767637/a3d58f24-c5dc-487e-8905-4b0ea9d67233)

config for nginx, don't setup...

**Comment by Linux123123** [comment]
Provide full logs
```bash
cat /var/log/pterodactyl-installer.log | nc termbin.com 9999
```

**Comment by TheFairwol** [comment]
https://termbin.com/peur

**Comment by TheFairwol** [comment]
[pterodactyl-installer.log](https://github.com/pterodactyl-installer/pterodactyl-installer/files/13383206/pterodactyl-installer.log)

**Comment by Linux123123** [comment]
![image](https://github.com/pterodactyl-installer/pterodactyl-installer/assets/26341983/5e3ee8b8-9673-465e-a75a-93e40a1b8c52)
```
* If you assume SSL and do not obtain the certificate, your installation will not work.
```

The script said it won't work until you provide valid SSL certificates. Also run the script only on a clean system, and preferably only run it once.
