### ISSUE TITLE
firewall feature potentially broken on Rocky & Alma

### ISSUE THREAD

**Issue by PixelMW** [pterodactyl-installer/pterodactyl-installer#447]
* Opening port 22 (SSH), 8080 (Wings Port), 2022 (Wings SFTP Port)
ERROR: initcaps
[Errno 2] ip6tables v1.8.4 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.

**Comment by TibsterDeveloper** [comment]
same

**Comment by Linux123123** [comment]
The firewall option on Rocky and Alma might be broken, just don't use it and if you need a firewall configure it yourself.

**Comment by vilhelmprytz** [comment]
@PixelMW @TibsterDeveloper Can you please confirm what distribution you were using when running into this problem?

**Comment by TibsterDeveloper** [comment]
im using ubuntu but the cloudspaces provided by github!

**Comment by TibsterDeveloper** [comment]
@vilhelmprytz i checked if it may be something with php or something but i get some iptables error

**Comment by vilhelmprytz** [comment]
@Linux123123 This issue itself is not related to Rocky & Alma it seems, but I think we still have a problem on Rocky & Alma. Maybe we can open a new issue for that specifically?

**Comment by vilhelmprytz** [comment]
I just tested this. Everything works on Rocky and Linux, solving.
