### ISSUE TITLE
mysql database error

### ISSUE THREAD

**Issue by 1gzify** [pterodactyl-installer/pterodactyl-installer#448]
im trying in the panel to create a database and i do create and it just doesnt do anything like it shows this "There was an error while trying to connect to the host or while executing a query: "SQLSTATE[HY000] [2002] Connection timed out (Connection: dynamic, SQL: SELECT 1 FROM dual)""

**Comment by vilhelmprytz** [comment]
Check the configuration, something is probably not correct. Refer to our [Discord server](https://pterodactyl-installer.se) for help with the script!
