### ISSUE TITLE
NOT WORK

### ISSUE THREAD

**Issue by MatiM72737** [pterodactyl-installer/pterodactyl-installer#450]
Actually it's totally not work
* Configure Firewall? false
* Configure Let's Encrypt? false
* Assume SSL? false
##############################################################

* Initial configuration completed. Continue with installation? (y/N): y
* Starting installation.. this might take a while!
* Installing dependencies for ubuntu 22.04...
Get:1 file:/cdrom jammy InRelease
Ign:1 file:/cdrom jammy InRelease
Get:2 file:/cdrom jammy Release
Err:2 file:/cdrom jammy Release
  File not found - /cdrom/dists/jammy/Release (2: No such file or directory)
Hit:3 http://pl.archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://pl.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://pl.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:6 http://pl.archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists...
E: The repository 'file:/cdrom jammy Release' no longer has a Release file.
root@pterodactyl:/home/pterodactyl#

**Comment by Linux123123** [comment]
Seems like your installation of the OS is not fully complete, as the cdrom sources should be removed after successful installation.
