### ISSUE TITLE
install fails on wings portion

### ISSUE THREAD

**Issue by GamingDaveUk** [pterodactyl-installer/pterodactyl-installer#455]
**Describe the bug**
The installation fails and wings is not installed (ight be as docker is installed by Amp, planning to try both panels)

**To Reproduce**
Steps to reproduce the behaviour:
run the script again choose option2

if I run it again it says pterodactyl is installed and asks if i would like to retry, i say no it then asks if i would like to continue to wings, i say yes and it gives me the same error as orinally so its a wings install error:

```
* Installing virt-what...
E: Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/ubuntu/ jammy: /etc/apt/keyrings/docker.gpg != /usr/share/keyrings/download.docker.com.gpg
E: The list of sources could not be read.
```

**Expected behaviour**
installation to be successful

**Screenshots**

**OS (please complete the following information):**

- OS: [e.g. Ubuntu, Debian, CentOS] ubuntu 22.04
- Installation: [panel or wings]
both
**Additional context**

Docker is installed and set up as part of Amp, i am using Amp at mo and planned to look at pterdactyle to see if it was better for certain games (conan is missing tons of config settings in amp) so far the installation issues is not putting pterodactyl in a good light, vut i suspect its due to docker already being installed...though if thats the case why does it error instead of just using that install? (I am not much of a linux user usually so maybe i am missing something obvious?)

EDIT: 
If i try to install wings by itself i get the error instantly:

```
root@Little:~# bash <(curl -s https://pterodactyl-installer.se)
* Retrieving release information...
######################################################################
* Pterodactyl panel installation script @ v1.0.0
*
* Copyright (C) 2018 - 2023, Vilhelm Prytz, <vilhelm@prytznet.se>
* https://github.com/pterodactyl-installer/pterodactyl-installer
*
* This script is not associated with the official Pterodactyl Project.
*
* Running ubuntu version 22.04.
######################################################################
* What would you like to do?
* [0] Install the panel
* [1] Install Wings
* [2] Install both [0] and [1] on the same machine (wings script runs after panel)
* [3] Install panel with canary version of the script (the versions that lives in master, may be broken!)
* [4] Install Wings with canary version of the script (the versions that lives in master, may be broken!)
* [5] Install both [3] and [4] on the same machine (wings script runs after panel)
* [6] Uninstall panel or wings with canary version of the script (the versions that lives in master, may be broken!)
* Input 0-6: 1
* Retrieving release information...
######################################################################
* Pterodactyl panel installation script @ v1.0.0
*
* Copyright (C) 2018 - 2023, Vilhelm Prytz, <vilhelm@prytznet.se>
* https://github.com/pterodactyl-installer/pterodactyl-installer
*
* This script is not associated with the official Pterodactyl Project.
*
* Running ubuntu version 22.04.
* Latest pterodactyl/wings is v1.11.8
######################################################################
* Installing virt-what...
E: Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/ubuntu/ jammy: /etc/apt/keyrings/docker.gpg != /usr/share/keyrings/download.docker.com.gpg
E: The list of sources could not be read.

```

**Comment by Linux123123** [comment]
The script doesn't check for any already installed software, as we expect the OS to be cleanly installed before using the script. If you are only trying to install wings and have docker preinstalled, just use [pterodactyl documentation](https://pterodactyl.io/wings/1.0/installing.html#installing-wings-2).

**Comment by Linux123123** [comment]
Closing for now, if you have more issues, please write in Discord.
