### ISSUE TITLE
Check utf-8 locales before script installation

### ISSUE THREAD

**Issue by pafade89** [pterodactyl-installer/pterodactyl-installer#456]
**Is your feature request related to a problem? Please describe.**

It would be very useful to query the locales in the script and if incorrect, switch to UTF-8 to ensure that Nginx receives its configuration and the /var/www/pterodactyl folder is created.

**Describe the solution you'd like**

Same as above
I find the feature request meaningful, as there have been several issues related to this in the repository both currently and in the past.

Example:
#445 
#436

**Comment by Linux123123** [comment]
Nginx in this case is completly unrelated. I do not see how setting locales would fix the issue, with database password. The issue with it is commonly special characters, character which don't get escaped and such which cause issues while creating the user. The best solution would be to have a regex for mysql password.

**Comment by pafade89** [comment]
I tried to install Pterodactyl with the script, which didn't work properly. It works only when I adjusted the locales to UTF-8 that your script ran smoothly.

**Comment by pafade89** [comment]
It is difficult to provide you with log files in this case, as your script runs without errors. However, no Nginx configuration is carried out, and the entire Pterodactyl data is not transferred. If you change the locale from C POSIX (ASCII) to the UTF-8 locale, then the script runs without errors again. This time, the Nginx configuration is made, and the Pterodactyl data is transferred correctly. The server starts thereafter and runs as expected.

The entire process was tested multiple times on a freshly installed Debian system with no prior configuration. Only the net install of Debian was performed.


Thank you in advanced 

P

**Comment by vilhelmprytz** [comment]
Sorry for the delay in this. I think the termbin link expired. If this is still an issue, can you upload the logs again from the installation process?

**Comment by pafade89** [comment]
@vilhelmprytz No problem. Here the new upload.

https://termbin.com/qa0g

**Comment by pafade89** [comment]
@vilhelmprytz 
Have you had a chance to look at it? I've uploaded the log again?

**Comment by pafade89** [comment]
I think this is no longer necessary with the new [pelican panel](https://pelican.dev/).
