### ISSUE TITLE
My script failed in between

### ISSUE THREAD

**Issue by magicgamer456** [pterodactyl-installer/pterodactyl-installer#457]
Idk how but 1 time this script worked but I accidentally placed a invalid IP and I want to change it to IP address so I opened the script again but then in the last step I guess a error prompt 

line 1 access denied for user root@localhost [using password = no]
For information I am doing this in github I tried like many methods but no success can your help me? Pls here is a screenshot if you need
![Screenshot_20240308-200030](https://github.com/pterodactyl-installer/pterodactyl-installer/assets/145262392/e1e6f4d2-1fc7-4e76-b435-79cf0458ae75)

**Comment by Linux123123** [comment]
You can't run the script 2 times in a row. You must remove pterodactyl first and then run again.

**Comment by magicgamer456** [comment]
I did that cleared all data but still its the same its not even my password issue I have only letters in my pass of root
