### ISSUE TITLE
Access denied for user 'root'@'local host'

### ISSUE THREAD

**Issue by magicgamer456** [pterodactyl-installer/pterodactyl-installer#458]
**Describe the bug**
A clear and concise description of what the bug is that this bug comes when The last step I guess in creating the databases and this error comes BTW I am doing this in github

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'installer'
2. Click on 'do all steps'
3. Scroll down to 'then at last when creating databases'

**Expected behaviour**
A clear and concise description of what you expected to happen is it should be successful

**Screenshots**

**OS :**

- OS: linux
- Installation: wing I guess

**Additional context**
Add any other context about the problem here I already opened this one time bit he closed it and didn't respond so I opened another one
![Screenshot_20240308-200030](https://github.com/pterodactyl-installer/pterodactyl-installer/assets/145262392/3e66103c-054c-4c4d-a83c-0e6eb85219cf)

**Comment by vilhelmprytz** [comment]
Please make sure you run the script on a clean system installation. Can you confirm that you ran the script on a clean system installation?

**Comment by vilhelmprytz** [comment]
This looks like GitHub Codespaces, which is not going to work with Pterodactyl anyways.

**Comment by magicgamer456** [comment]
Let me just clear all stuff and try

**Comment by vilhelmprytz** [comment]
@Andrew-Cumming What distribution were you using when installing?

**Comment by xSmair** [comment]
I completely removed redis, mariadb and mysql. Anyways I am getting this 
`Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi || true

   INFO  Discovering packages.

  laracasts/utilities ................................................... DONE
  laravel/sanctum ....................................................... DONE
  laravel/tinker ........................................................ DONE
  laravel/ui ............................................................ DONE
  nesbot/carbon ......................................................... DONE
  nunomaduro/termwind ................................................... DONE
  prologue/alerts ....................................................... DONE
  spatie/laravel-fractal ................................................ DONE
  spatie/laravel-query-builder .......................................... DONE

69 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

* SUCCESS: Installed composer dependencies!

* Creating database user pterodactyl...
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'pterodactyl'@'127.0.0.1'
* Installation of panel completed. Do you want to proceed to wings installation? (y/N):`
