### ISSUE TITLE
Skipping Let's Encrypt installation

### ISSUE THREAD

**Issue by Multizuka** [pterodactyl-installer/pterodactyl-installer#461]
**Ubuntu 20.04**
When installing the panel.

using the command:
`bash <(curl -s https://pterodactyl-installer.se)`

When installed, it skips the **Let's Encrypt** configuration.

After the email question, the installation of the panel begins immediately. Installs without errors, everything works except **Let's Encrypt**

Now I'm trying to install it manually, using certbot, but there is no result.
I’m not waiting for an answer, I’ll try to solve it myself, but I decided to report this situation

(_I didn’t attach the console because there are no errors in it_)

**Comment by Linux123123** [comment]
The installer definitely doesn't skip let's encrypt, if you choose to enable SSL, and not assume SSL. Closing until you provide logs where specific choices are made in the script and it doesn't run `certbot`.
