### ISSUE TITLE
lib.sh

### ISSUE THREAD

**Issue by Elegantbitecatering** [pterodactyl-installer/pterodactyl-installer#463]
when I do bash <(curl -s https://petrodactyl-installer.se) it sates /dev/fd/63: line 48; /tmp/lib.sh: No such file directory

**Comment by RedNotSus** [comment]
you need to be sudo
do
`sudo su`

and try again

**Comment by Elegantbitecatering** [comment]
still saying it

**Comment by Elegantbitecatering** [comment]
I figured it out on my own.
