### ISSUE TITLE
ERROR 1146 (42S02) at line 1: Table 'mysql.user' doesn't exist

### ISSUE THREAD

**Issue by zNitrx** [pterodactyl-installer/pterodactyl-installer#464]
I have two issues:

1st one:
I am installing wings and after installing systemd service, it starts Configuring MYSQL, but then, when I create a DB user, it says that the table "mysql.user" doesn't exist
- OS: Ubuntu
- Installation: Wings
Screenshot:
![image](https://github.com/pterodactyl-installer/pterodactyl-installer/assets/106552682/4ca1645f-676a-4350-ae98-389ad04c798b)
![image](https://github.com/pterodactyl-installer/pterodactyl-installer/assets/106552682/ce5b6a42-d701-4255-89d3-6f2956ab7bb8)
-----------------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------------------------
2nd one:
After installing it correctly (Without a User DB because an ERROR 1146 was shown), when I try to get to the panel GUI, I can't. The domain just doesn't work, so I can't configure wings.
Also, when I try "sudo nginx", I get some errors:

nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] still could not bind()

Also, the pterodactyl logs:
https://pastebin.com/W3cznqLh
- OS: Ubuntu
- Installation: Wings
Screenshot:
![image](https://github.com/pterodactyl-installer/pterodactyl-installer/assets/106552682/e979633b-ac16-4b75-b24e-5d7cb4856e48)

**Comment by Connor200024** [comment]
I'm getting the same issue as well. I could try and install an older version of pterodactyl and see if this works. But unsure. :)

**Comment by Linux123123** [comment]
Install on a clean system (without any other software) and set up your DNS correctly.
