### ISSUE TITLE
GPG error installation Debian 12 [the public key is not available]

### ISSUE THREAD

**Issue by GTX6717** [pterodactyl-installer/pterodactyl-installer#469]
GPG error installation

Version : Debian 12 with apache

I selected Install both [0] and [1] on the same machine (wings script runs after panel)

I completed the script and after validate the last option i have this error.

W: GPG error: https://packages.redis.io/deb bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5F4349D6BF53AA0C

E: The repository 'https://packages.redis.io/deb bookworm InRelease' is not signed.

and the installation is not starting.

**Comment by Linux123123** [comment]
We do not support `apache2` as an installation option, and also we don't use the specific repository that is causing your error. Please reinstall your OS, and run the script on a clean system. We use Redis from Debian repositories.
