### ISSUE TITLE
Error when obtaining certificate for wings 

### ISSUE THREAD

**Issue by ZacBozer** [pterodactyl-installer/pterodactyl-installer#470]
* Configuring LetsEncrypt..
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
An unexpected error occurred:
The request message was malformed :: No such authorization
Please see the logfiles in /var/log/letsencrypt for more details.

* WARNING: The process of obtaining a Let's Encrypt certificate failed!

**Comment by Linux123123** [comment]
`certbot` is not maintained by us, so I can't say what exactly went wrong. Try obtaining certificates manually, make sure all DNS is configured properly.
