### ISSUE TITLE
Nodes Red/ Installer Bug Nodes Don't Want to Be Green

### ISSUE THREAD

**Issue by wndrzzka** [pterodactyl-installer/pterodactyl-installer#474]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**OS (please complete the following information):**

- OS: [e.g. Ubuntu, Debian, CentOS]
- Installation: [panel or wings]

**Additional context**

**Comment by Linux123123** [comment]
Provide more information about issue.

**Comment by Linux123123** [comment]
Reopen, when you provide more information.
