### ISSUE TITLE
I got this error. Is it usually fixed?

### ISSUE THREAD

**Issue by XM4ZE** [pterodactyl-installer/pterodactyl-installer#475]
INFO: [May  5 14:54:10.311] loading configuration from file config_file=/etc/pterodactyl/config.yml
 INFO: [May  5 14:54:10.311] configured wings with system timezone timezone=Etc/UTC
 INFO: [May  5 14:54:10.311] checking for pterodactyl system user username=pterodactyl
 INFO: [May  5 14:54:10.311] configured system user successfully gid=997 uid=997 username=pterodactyl
 INFO: [May  5 14:54:10.313] fetching list of servers from API
FATAL: [May  5 14:54:29.656] failed to load server configurations error=http: request creation failed: Get "/api/remote/servers                                                                                                                              ?page=0&per_page=50": unsupported protocol scheme ""

Stacktrace:
Get "/api/remote/servers?page=0&per_page=50": unsupported protocol scheme ""
http: request creation failed
github.com/pterodactyl/wings/remote.(*client).request.func1
        github.com/pterodactyl/wings/remote/http.go:151
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer.Operation.withEmptyData.func1
        github.com/cenkalti/backoff/v4@v4.3.0/retry.go:18
github.com/cenkalti/backoff/v4.doRetryNotify[...]
        github.com/cenkalti/backoff/v4@v4.3.0/retry.go:88
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer
        github.com/cenkalti/backoff/v4@v4.3.0/retry.go:61
github.com/cenkalti/backoff/v4.RetryNotify
        github.com/cenkalti/backoff/v4@v4.3.0/retry.go:49
github.com/cenkalti/backoff/v4.Retry
        github.com/cenkalti/backoff/v4@v4.3.0/retry.go:38
github.com/pterodactyl/wings/remote.(*client).request
        github.com/pterodactyl/wings/remote/http.go:136
github.com/pterodactyl/wings/remote.(*client).Get
        github.com/pterodactyl/wings/remote/http.go:81
github.com/pterodactyl/wings/remote.(*client).getServersPaged
        github.com/pterodactyl/wings/remote/servers.go:201
github.com/pterodactyl/wings/remote.(*client).GetServers
        github.com/pterodactyl/wings/remote/servers.go:26
github.com/pterodactyl/wings/server.(*Manager).init
        github.com/pterodactyl/wings/server/manager.go:238
github.com/pterodactyl/wings/server.NewManager
        github.com/pterodactyl/wings/server/manager.go:36
github.com/pterodactyl/wings/cmd.rootCmdRun
        github.com/pterodactyl/wings/cmd/root.go:138
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.0/command.go:987
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/pterodactyl/wings/cmd.Execute
        github.com/pterodactyl/wings/cmd/root.go:71
main.main
        github.com/pterodactyl/wings/wings.go:17
runtime.main
        runtime/proc.go:267
runtime.goexit
        runtime/asm_amd64.s:1650

**Comment by Linux123123** [comment]
New wings release has fixed this, closing.
