### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by martinelcrac** [pterodactyl-installer/pterodactyl-installer#476]
* Initial configuration completed. Continue with installation? (y/N): y
* Starting installation.. this might take a while!
* Installing dependencies for debian 11...
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 https://dl.google.com/linux/chrome/deb stable InRelease
Get:5 https://packages.microsoft.com/repos/code stable InRelease [3,590 B]
Get:6 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
Hit:7 http://ppa.launchpad.net/ondrej/php/ubuntu noble InRelease
Hit:8 https://apt.postgresql.org/pub/repos/apt bullseye-pgdg InRelease
Hit:10 https://packages.redis.io/deb bullseye InRelease
Get:11 https://dlm.mariadb.com/repo/mariadb-server/11.2/repo/debian bullseye InRelease [4,637 B]
Hit:12 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/bullseye pgadmin4 InRelease
Get:13 https://dlm.mariadb.com/repo/maxscale/latest/apt bullseye InRelease [9,341 B]
Err:6 https://deb.nodesource.com/node_20.x nodistro InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2F59B5F99B1BE0B4
Hit:9 https://downloads.mariadb.com/Tools/debian bullseye InRelease
Reading package lists...
W: GPG error: https://deb.nodesource.com/node_20.x nodistro InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2F59B5F99B1BE0B4
E: The repository 'https://deb.nodesource.com/node_20.x nodistro InRelease' is not signed.

**Comment by Linux123123** [comment]
We do not add the repositories that are failing. Install on a clean system.
