### ISSUE TITLE
Missing release file on Debian 11

### ISSUE THREAD

**Issue by shahirblue** [pterodactyl-installer/pterodactyl-installer#478]
When trying to install Pterodactyl Panel with the script on Debian 11:
"E: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu oracular Release' does not have a Release file."

<img width="780" alt="image" src="https://github.com/pterodactyl-installer/pterodactyl-installer/assets/169415697/32433efc-a454-426d-b280-6254543fb50f">

**Comment by Linux123123** [comment]
We do not use Ubuntu PPA on Debian. Install on a clean system.
