### ISSUE TITLE
Installing virt-what, after that script closes

### ISSUE THREAD

**Issue by PrevikYT** [pterodactyl-installer/pterodactyl-installer#479]
1. Lauched script
2. Selected "wings install"

* Installing virt-what...
W: https://repo.mongodb.org/apt/ubuntu/dists/jammy/mongodb-org/6.0/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://repo.mongodb.org/apt/ubuntu/dists/bionic/mongodb-org/4.2/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 Release: The following signatures were invalid: EXPKEYSIG 4B7C549A058F8B6B MongoDB 4.2 Release Signing Key <packaging@mongodb.com>
E: Failed to fetch http://uk-london-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports/dists/jammy/main/binary-amd64/Packages  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://uk-london-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports/dists/jammy-updates/main/binary-amd64/Packages  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/jammy-security/main/binary-amd64/Packages  404  Not Found [IP: 185.125.190.36 80]
E: Failed to fetch http://uk-london-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports/dists/jammy-backports/main/binary-amd64/Packages  404  Not Found [IP: 185.125.190.39 80]
W: Failed to fetch https://repo.mongodb.org/apt/ubuntu/dists/bionic/mongodb-org/4.2/Release.gpg  The following signatures were invalid: EXPKEYSIG 4B7C549A058F8B6B MongoDB 4.2 Release Signing Key <packaging@mongodb.com>
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/main/binary-arm64/Packages  404  Not Found [IP: 91.189.91.81 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.

Ubuntu 22.04 oracle cloud

**Comment by Linux123123** [comment]
The repositories, in your logs, are not added by the script. Please install on a clean system.
