### ISSUE TITLE
Wing installation crashed

### ISSUE THREAD

**Issue by magicgamer456** [pterodactyl-installer/pterodactyl-installer#486]
**Describe the bug**
A clear and concise description of what the bug is. The I was install in wing at last and this happened no idea what this means

**To Reproduce**
Steps to reproduce the behaviour:

Idk about this
**Expected behaviour**
A clear and concise description of what you expected to happen. For it continue with the installation

**Screenshots**
If applicable, add screenshots to help explain your problem. I added 1

**OS (please complete the following information):**

- OS: Debian 12
- Installation: wing

**Additional context**
Add any other context about the problem here. Remember this is a not a github machine or any other this is a VM
![Uploading Screenshot_20240613-223125.png…]()

**Comment by magicgamer456** [comment]
The IMG didnt get uploaded here's a new one
![Uploading Screenshot_20240613-223125.png…]()

**Comment by vilhelmprytz** [comment]
@magicgamer456 There is no image attached to the issue and no other debug information. Can you provide more debug information and context about your problem?

**Comment by vilhelmprytz** [comment]
Closing this issue for now. Feel free to reopen if you have more details to provide about the problem.
