### ISSUE TITLE
Installer wont run on ubuntu 24.04

### ISSUE THREAD

**Issue by kweeks95** [pterodactyl-installer/pterodactyl-installer#488]
**Describe the bug**
when attempting to run the installer via the command provided im prompted with an error message stating that ubuntu 24.04 is not supported ERROR: Unsupported OS.

It says on the home page of the pterodactyl-installer that ubuntu 24.04 is supported so im not sure why this is an issue.

**Expected behaviour**
expect the installer to run and prompt with install options

**Screenshots**

**OS (please complete the following information):**

- OS: Ubuntu Server 24.04
- Installation: [panel or wings]

**Additional context**

**Comment by Linux123123** [comment]
Use the canary version of the script.

**Comment by NewittAll** [comment]
How? The installer doesn't say how, and not providing a solution doesn't help.

**Comment by Linux123123** [comment]
Sorry, yes, the issue still persists as OS compatibility is still checked before the selection is allowed.

Here I have quickly changed the branch from which it pulls `lib.sh`

```sh
bash <(curl -s https://gist.githubusercontent.com/Linux123123/0c749c6bccfe812d4d28be0633e26d72/raw/0df407889d4ec75d70028eb2d9e99ba83d609f81/install.sh)
```

**Comment by vilhelmprytz** [comment]
@Linux123123 Can we do a long-term fix for this so that `lib.sh` is actually fetched from canary branch when canary version is selected by user?

**Comment by Linux123123** [comment]
Yes, it's an oversight in m design of this `install.sh` with `lib.sh`. We would always need to fetch canary `lib.sh` at first and only after selecting a specific option refetching the correct version (canary/release), basically the other way around than we have now.
