### ISSUE TITLE
Add a option to setup panel and wings behind Cloudflare proxy 

### ISSUE THREAD

**Issue by abhi634367** [pterodactyl-installer/pterodactyl-installer#496]
Add a option to setup panel and wings behind Cloudflare proxy not just dns only

**Comment by siroo2137** [comment]
you can set it up in the panel itself when configuring a node

**Comment by Linux123123** [comment]
The problem with running wings behind CF proxy is that people will only be able to access their servers and, by extension, SFTP using the subdomain. That is because Cloudflare's free plans don't allow ports other than a few HTTP ones, through.
