### ISSUE TITLE
Unattended install

### ISSUE THREAD

**Issue by siroo2137** [pterodactyl-installer/pterodactyl-installer#497]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Be able to set enviroment variables to pre-set the installation settings, type, etc

**Describe alternatives you've considered**
None

**Additional context**
n/a

**Comment by Linux123123** [comment]
It is already possible to do unattended installs, by presetting bash environment variables for a specific script in the installation folder, for example https://github.com/pterodactyl-installer/pterodactyl-installer/blob/master/installers/panel.sh. 

The variables are listed under [# ------------------ Variables ----------------- #](https://github.com/pterodactyl-installer/pterodactyl-installer/blob/6d6e506f08c8609a7e6acec9b3cddaad93062ddb/installers/panel.sh#L39) and if you set GITHUB_BASE_URL, GITHUB_SOURCE (branch) and all the required variables, it will automatically fetch `lib.sh` and install it for you.
