### ISSUE TITLE
Installing panel only blocking requests from ISP router after install? Lose Proxmox web interface

### ISSUE THREAD

**Issue by oppdelta** [pterodactyl-installer/pterodactyl-installer#501]
**Describe the bug**
Installed Panel only option [0]. All successfull in shell, but webinterface timed out, go to refresh and it no longer loads. All other VMs running work, can access NAS, nginx proxy, just not https://192.168.1.5:8006 

Have access to Proxmox shell, and running `journalctl -b -e` shows:   
`<node>_ kernel: [UFW BLOCK] IN=vmbr0 OUT= MAC= (MY PC's MAC ADDRESS) SRC=192.168.1.1`

**To Reproduce**
Steps to reproduce the behaviour:

1. Install Ptero Panel with Lets Encrypt on.

**Expected behaviour**
To not overwrite my firewall?

**Screenshots**
https://imgur.com/a/vBcnlZB

**OS (please complete the following information):**

- OS: Debian / Proxmox
- Installation: Panel

**Additional context**
Stopped teh firewall (I think), but connection still blocked?

**Comment by oppdelta** [comment]
Disabling the firewall, adding a rule to 192.168.1.1, 192.168.1.5, 192.168.1.111, then `ufw enable` worked appears to have worked.

**Comment by oppdelta** [comment]
Found the issue, unable to figure out how to resolve.

I already had nginx installed in another container. But this install script installed another ngix WITHIN my proxmox installation? WHAT? My Proxmox instal runs on 192.168.1.5, navigating to that in the browser which always timedout. Now I went to it accidentally (Forgot the 8006) and ngix wants to do a setup? 

How do I remove all the crap this script has put on my OS? The uninstaller option did nothing, remove the ngix instal you did...

**Comment by sinjs** [comment]
The script [asks if you want to set up the firewall](https://github.com/pterodactyl-installer/pterodactyl-installer?tab=readme-ov-file#firewall-setup), and you agreed to that. All the "other" crap that the script has put on your operating system is required for the Pterodactyl panel to function. The script installs the nginx webserver which then runs the panel.

**Comment by Linux123123** [comment]
This is not a problem with the script. Nginx is required for pterodactyl to work, and if you want to expose only php-fpm and use an already existing Nginx server, you need to install Pterodactyl manually.
