### ISSUE TITLE
Giving Repository ERRORS from a OS Website that im not even using that OS for

### ISSUE THREAD

**Issue by theikemaster22** [pterodactyl-installer/pterodactyl-installer#504]
ERROR:
The repository 'https://download.docker.com/linux/ubuntu bookworm Release' does not have a Release file

Install using Let's Encrypt
After it asks to configure HTTPS(likely when it tries to install
you recieve the error

ERROR: The repository 'https://download.docker.com/linux/ubuntu bookworm Release' does not have a Release file

unable to provide screenshots

- OS: Debian
- Installation: Panel Phase

i might just make an ubuntu docker image and see if that changes my error, i assume i will still have issues considering that would be docker on docker

**Comment by Mailootje** [comment]
No its the repository thats not working / has no release...

**Comment by Linux123123** [comment]
Install on clean OS. You are trying to install Ubuntu packages on Debian.
