### ISSUE TITLE
Node not connecting

### ISSUE THREAD

**Issue by Brozovec** [pterodactyl-installer/pterodactyl-installer#506]
**Describe the bug**
Hi i just instaled pterodactil panel and when i created node it says not connecting chceck web console there it says Failed to load resource: net::ERR_CONNECTION_REFUSED.

**Screenshots**
![image](https://github.com/user-attachments/assets/97f237a8-a458-4453-af2a-bf8142672a25)
![image](https://github.com/user-attachments/assets/69bf4904-4408-4b43-bcd5-21b92cf3ecaa)

**OS Ubuntu 22.04**

- Installation: both

**Comment by Brozovec** [comment]
I have fixed it now i have problem when i try to create database host it says this 

There was an error while trying to connect to the host or while executing a query: "SQLSTATE[HY000] [1130] Host '51.68.174.52' is not allowed to connect to this MariaDB server (Connection: dynamic, SQL: SELECT 1 FROM dual)"

**Comment by sinjs** [comment]
This means that the user is only allowed to be connected via a different IP-Address. You can create a new user that allows access from any IP-Address using the following SQL command:

```sql
CREATE USER 'my_username'@'%' IDENTIFIED BY 'my_password';
```

**Comment by vilhelmprytz** [comment]
This is not a problem with the script. Refer to our Discord server for help with the script. Closing.
