### ISSUE TITLE
ERROR: bash: /dev/fd/63: No such file or directory

### ISSUE THREAD

**Issue by Crazygiscool** [pterodactyl-installer/pterodactyl-installer#510]
**Describe the bug**
when executing the installation script, give 'bash: /dev/fd/63: No such file or directory' error

**To Reproduce**
Steps to reproduce the behaviour:
proxmox scsi0 drive
1. type 'cd'
2. type script 'bash <(curl -s https://pterodactyl-installer.se)'

**Expected behaviour**
installation of the panel

**OS (please complete the following information):**

- OS: Ubuntu Server 24.04
- Installation: panel

**Comment by Linux123123** [comment]
Use `sudo su` or `sudo -i` before running the script.

**Comment by SebRHQ** [comment]
Hi! Im having the same thing, sudo -i or sudo su does not fix the problem for me

**Comment by Tbizla** [comment]
Same boat,

`sudo` su and `sudo -i` didn't work for me

**Comment by vilhelmprytz** [comment]
Duplicate of #1, #29, #171, #205, #246, #311, #355, #386, #403, #441, #453, #460, #463 and #508 🙂 I probably missed a few other issues. Feel free to reopen if this is not the case.

**Comment by Crazygiscool** [comment]
tysm guys, I used https://pterodactyl-installer.se/i.sh and it worked
