### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by tbhbestdevman** [pterodactyl-installer/pterodactyl-installer#515]
**Describe the bug**
The Database user isn't created
**To Reproduce**
Steps to reproduce the behaviour:

1. install wings and panel
2. put in information ( random database password/blank)
3. Install and get error
**Expected behaviour**
this is the output
```
--------------
CREATE USER 'pterodactyl'@'127.0.0.1' IDENTIFIED BY 'ME~!AYwVkD4}O-G"ikKfe>5zpe,cF@xR[WwAMgHT^h5qJ7#Ytc71Kx&3{P,]b.t%'
--------------

ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'pterodactyl'@'127.0.0.1'
```
**Screenshots**

**OS (please complete the following information):**
Debian 12
- OS: [e.g. Ubuntu, Debian, CentOS]
- Installation: [panel or wings]
both but this was the panel portion
**Additional context**

**Comment by Linux123123** [comment]
Please reopen the issue if the problem persists after trying to use a not-generated password.

**Comment by tbhbestdevman** [comment]
> Have you tried using a non-generated password and putting in your own?
Apologies for the delay in responding! I tested this further and found that using a custom password works fine, but the issue specifically occurs with generated passwords in the script. I hope this helps clarify the behavior. Thanks for checking into this!
