### ISSUE TITLE
missing repositories or not avaliable

### ISSUE THREAD

**Issue by RAGGIDYrgb** [pterodactyl-installer/pterodactyl-installer#517]
I keep getting errors when trying to install both ptero and wings at the same time. haven't tried them separately.

OS: Ubuntu server 24.10

* Initial configuration completed. Continue with installation? (y/N): y
* Starting installation.. this might take a while!
* Installing dependencies for ubuntu 24.10...
Hit:1 http://us.archive.ubuntu.com/ubuntu oracular InRelease
Hit:2 http://security.ubuntu.com/ubuntu oracular-security InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu oracular-updates InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu oracular-backports InRelease
Ign:5 https://ppa.launchpadcontent.net/ondrej/php/ubuntu oracular InRelease
Err:6 https://ppa.launchpadcontent.net/ondrej/php/ubuntu oracular Release
  404  Not Found [IP: 185.125.190.80 443]
Reading package lists...
E: The repository 'https://ppa.launchpadcontent.net/ondrej/php/ubuntu oracular R                                                                                                                                                             elease' does not have a Release file.
* Installation of panel completed. Do you want to proceed to wings installation?                                                                                                                                                              (y/N): y
* Retrieving release information...
######################################################################
* Pterodactyl panel installation script @ v1.1.1
*
* Copyright (C) 2018 - 2024, Vilhelm Prytz, <vilhelm@prytznet.se>
* https://github.com/pterodactyl-installer/pterodactyl-installer
*
* This script is not associated with the official Pterodactyl Project.
*
* Running ubuntu version 24.10.
* Latest pterodactyl/wings is v1.11.13
######################################################################
* Installing virt-what...
E: The repository 'https://ppa.launchpadcontent.net/ondrej/php/ubuntu oracular R                                                                                                                                                             elease' does not have a Release file.

**Comment by Linux123123** [comment]
The script does not support Ubuntu 24.10
