### ISSUE TITLE
Install does not proceed

### ISSUE THREAD

**Issue by FallconTXoC** [pterodactyl-installer/pterodactyl-installer#519]
**Describe the bug**
When trying to install both Panel and Wings either separately or at the same time (normal and Canary versions alike) the script will only run apt update and not proceed with the installation of anything. It says Panel was installed successfully (although it doesn't) and when I tell it to proceed to Wings install, it stops after the apt update with no additional context.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go into root with sudo su
2. Run the script using `bash <(curl -s https://pterodactyl-installer.se)`
3. Run any install option.
4. Configure by following the prompts
5. Proceed to install
6. Script stops with no error but also no install

**Expected behaviour**
As shown in the demo video, the script should be installing and configuring the required tools for both Panel and Wings. These installs are supposed to print logs in the running terminal instance so I assume, along with the fact that nothing is running and nothing is detected to be uninstalled when running the uninstall option, that it did not in fact install anything.

**Screenshots**
![image](https://github.com/user-attachments/assets/f1c50621-c68f-498c-afcf-26943512fc32)

**OS (please complete the following information):**

- OS: Ubuntu 22.04
- Installation: Both Panel and Wings

**Comment by Linux123123** [comment]
Please run the script on a clean system. (The script does not install the pulse effects repository seen in your screenshot, which is why the script is failing)
